spring:
  datasource:
    url: jdbc:h2:file:~/h2_data/core
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    platform: h2


  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

