
spring:
  masterdatasource:
    url: jdbc:mysql://106.12.201.12:3311/cbvac
    username: root
    password: fNty2u8awl
    platform: mysql
  slavedatasource:
    url: jdbc:mysql://106.12.201.12:3311/cbvac
    username: root
    password: fNty2u8awl
    platform: mysql
  application:
    name: CbvacWebApplication
